### PR TITLE
Merging Inventory-Logic to Main

### PR DESCRIPTION
**Pull request by cothon01**
Summary:
- Items
- Inventory manager
- Weapon Data
- Collectibles
- Collecting Action
- etc

### CODE REVIEW

**Review by Helcostr — CHANGES_REQUESTED** [review]
Can't touch `SampleScene.unity` that's a public file.

**Review by Helcostr — APPROVED** [review]
Minimal disruption on common files. All good.

**Review by Sneakydeaky — APPROVED** [review]
Every thing looks good, only thing id say is if you could name your file with the scenes something like "Inventory test" or something distinguishable that be awesome :)

**Comment by Helcostr** [comment]
I wonder if the one team two approving reviews is actually a buggy system... 🤔

**Comment by Helcostr** [comment]
Overriding x2 review requirement

**Pull request merged**
