### PR TITLE
v0.1 - Uploaded PlayerHud

### PR DESCRIPTION
**Pull request by tloonTFS**
++ Created PlayerHUD scene.
++ Created PlayerHUD UI canvas.
++ Unity 2D Sprite Package.
++ Uploaded PlayerHUD UI assets.
++ PlayerHUDManager script.
++ 3 Test scripts (EnemySpawner, PlayerHealth and WeaponSwap).

-- Bullet Scene, Scripts and Prefabs.

### CODE REVIEW

**Comment by tloonTFS** [comment]
Function works, still waiting for official scripts for player health and for weapons.

Will need and like to retouch PlayerHUD as things develop over time.

**Review by Helcostr — CHANGES_REQUESTED** [review]
image
Timers can overflow in space.

There are no easy switches to demonstrate how your numbers input your script. Please change.

**Comment by Helcostr** [comment]
Max Health is not linked to the bar.

**Review by cothon01 — APPROVED** [review]
Approved for merging.
Christos stamp of approval.

**Comment by Helcostr** [comment]
please resolve conflicts

**Review by Helcostr — APPROVED** [review]
looks good from a code perspective.

**Review by cothon01 — APPROVED** [review]
Approved

**Pull request merged**
