### PR TITLE
Adding name for assignment

### PR DESCRIPTION
**Pull request by P1xelslayer**
-David Obasi or Pixelslayer
adding name to the github

### CODE REVIEW

**Comment by Helcostr** [comment]
nice workaround ahahaha. i see you forked. give me a minute to reconsile permissions.

**Comment by Helcostr** [comment]
Permissions have been made, however, you can still use this branch to push. Please request me as someone to review when you are ready.

**Comment by P1xelslayer** [comment]
wait review. Hold up did I not finish?

**Comment by Helcostr** [comment]
> wait review. Hold up did I not finish?

- Make the changes you want to make
- Make the pull request
- Add a code reviewer (me) to the pull request
- Make any changes that are requested by the code reviewer as needed

Once this is done, the code reviewer takes over and merges it into the Master.

**Comment by P1xelslayer** [comment]
You got a second this week to go through with me by chance?

**Comment by Helcostr** [comment]
Totally!

**Review by Helcostr — CHANGES_REQUESTED** [review]
Please insert this into the folder Assignment 1.

**Review by Helcostr — APPROVED** [review]
Good job!

**Pull request merged**
