### PR TITLE
Enemy tank behaviour

### PR DESCRIPTION
**Pull request by Jeroldine**
Summary:
Created an enemy tank game object with AI. Enemy also has a attack box

Details:
- Tank will chase enemy
- Rotate to face the direction it is travelling
- Debug message when player enters the enemy attack box

Bug Fixes:

Deleted:

### CODE REVIEW

**Review by Helcostr — CHANGES_REQUESTED** [review]
Is it intentionally to knock the enemy down with physics?

**Comment by Jeroldine** [comment]
@Helcostr  can you give me a scenario to try for myself? I'm not sure what you are asking

**Comment by Helcostr** [comment]
ram yourself into the enemy.

**Comment by Jeroldine** [comment]
The behaviour seems expected since the TestPlayer only has a collider (no RigidBody) and the EnemyTank has a collider and RigidBody, so the EnemyTank will always get pushed out of the way.

**Comment by Helcostr** [comment]
> The behaviour seems expected since the TestPlayer only has a collider (no RigidBody) and the EnemyTank has a collider and RigidBody, so the EnemyTank will always get pushed out of the way.

that is the root issue, i was wondering do we want that? do we want to lock rotation? by design, we can modify the way it behaves.

**Comment by Jeroldine** [comment]
The Enemy tank has CharacterController component now instead of Rigid body. This got rid of the weird rotations and being pushed into the ground when colliding with the player. The enemy is still pushed out of the way of the player

**Comment by Helcostr** [comment]
There are conflicting issues that need to be resolved. please double check this.

**Pull request merged**
