### PR TITLE
Carter hopkins level design spawners added

### PR DESCRIPTION
**Pull request by thatonenerdd**
Summary: Added spawners to the level as well as the enemy prefabs.

Details: Exactly as the title states. Enemy prefabs dont have their scripts attached, to be fixed ASAP.

Bug Fixes:

Deleted:

### CODE REVIEW

**Comment by thatonenerdd** [comment]
Forgot to mention in the request, I also added red planes to the spawners so the player could at least tell where the enemies are supposed to come from.

**Review by Jeroldine — CHANGES_REQUESTED** [review]
It looks good. The plane for Spawner 4 flickers. I think if it is raised in the y-direction it will be okay

**Comment by thatonenerdd** [comment]
Resolved Flickering Spawner issue

**Review by cothon01 — APPROVED** [review]
Looks good 👍

**Review by Jeroldine — APPROVED** [review]
Looks good

**Pull request merged**
