### PR TITLE
Added Smoothness and Shake

### PR DESCRIPTION
**Pull request by Moseph90**
Camera moves more smoothly rather than abruptly. Also added a coroutine for camera shake people can use. In the example, I made it so that if you hit one of the large objects the camera shakes just to demonstrate. Coroutine also takes duration and magnitude parameters so that people can decide how much they want and for how long when they call it.

### CODE REVIEW

**Comment by Moseph90** [comment]
Also, didn't add it to the main level just yet because the terrain is missing and the player just falls through. Carter has already made a pull request with the fix. As soon as it's approved by someone else, I will jump in and implement.

**Comment by Helcostr** [comment]
@Moseph90 what's your scene to demonstrate camera shake?

**Comment by Moseph90** [comment]
> @Moseph90 what's your scene to demonstrate camera shake?

Same scene, Camera Test Scene. Just run into one of the bigger objects and you'll see the camera shake

**Review by cothon01 — APPROVED** [review]
Camera smoothing works.
Cool shake effect 👍

**Pull request merged**
