### PR TITLE
Enemy Spawner

### PR DESCRIPTION
**Pull request by JacyWhitfield**
Summary: Clean up

Details: Deleted some debug logs and cleaned up spacing

Bug Fixes:

Deleted: Debug logs

### CODE REVIEW

**Review by cothon01 — CHANGES_REQUESTED** [review]
Add a Start() method in your EnemySpawner to set variables (like the wave number) to 0 when the scene starts.

**Comment by JacyWhitfield** [comment]
added a start function and made the wave start at 1 and only start 10seconds after the game is loaded

**Review by cothon01 — APPROVED** [review]
All good 👍

**Comment by Helcostr** [comment]
Please resolve the conflicts.

**Comment by JacyWhitfield** [comment]
I don't understand, it conflicts because I'm replacing the script and changed some things?

**Review by Jeroldine — APPROVED** [review]
Looks good. Easy to swap out enemy prefabs.

**Pull request merged**
