### PR TITLE
Main camilo

### PR DESCRIPTION
**Pull request by Camilooh**
Added Main Menu test scene

### CODE REVIEW

**Review by Sneakydeaky — CHANGES_REQUESTED** [review]
I'm getting a Version mismatch when opening on unity. please confirm editor version :)

**Comment by Camilooh** [comment]
I am using 2022.3.10f1

**Comment by Helcostr** [comment]
> I'm getting a Version mismatch when opening on unity. please confirm editor version :)

@sneakydeaky i believe that Camilooh is using the TextPro module? that might be the issue... haven't taken a closer look

**Comment by Camilooh** [comment]
Yeah I am using TMPro

**Review by Helcostr — CHANGES_REQUESTED** [review]
@Camilooh You didn't actually start from the right node: this branch was not up to date, and didn't even contain a basic project (this was started before a unity project was created)

this has now been resolved. next time, please make sure to make a new branch starting from the right "node"

----

Do you think you need to do this to your canvas so that it always looks the way you want it to? 
image

**Comment by Camilooh** [comment]
@Helcostr oh so thats what happened, sorry about that still trying to fully understand how version control with GitHbu work. So just to be clear do you need me to do something else regarding this pull request or was everything solved?

**Comment by Helcostr** [comment]
> stand how version control with GitHbu work. So just to be clear do you need me to do something else regarding this pull request or was everything solved?

I am curious if you want to implement the canvas to make sure that it will scale... (part 2 of my comment)

**Comment by Camilooh** [comment]
> > stand how version control with GitHbu work. So just to be clear do you need me to do something else regarding this pull request or was everything solved?
> 
> I am curious if you want to implement the canvas to make sure that it will scale... (part 2 of my comment)

oh yeah I can do that

**Review by cothon01 — APPROVED** [review]
Added Canvas Scaling and fixed some text.
The transition between scenes works as intended.

**Pull request merged**
