### PR TITLE
Movement Scripts

### PR DESCRIPTION
**Pull request by Sneakydeaky**
Fixed Reviewers Requests.

### CODE REVIEW

**Review by cothon01 — CHANGES_REQUESTED** [review]
Movement interferes with dash ability.

**Review by Helcostr — CHANGES_REQUESTED** [review]
Please Name Test Scene to be more specific: probably "Movement Test Scene"

**Review by cothon01 — APPROVED** [review]
Movement and dashing works as intended.
All good 👍

**Review by Helcostr — APPROVED** [review]
requested changes were fixed.

**Pull request merged**
